Development
NeerNim/enumerable pull request #1
Opened 2019-05-24 22:33 UTC by NeerNim

2019-05-27 04:04 UTC, inhaq requested changes
Good job.
All methods are working as expected except `my_each` and `my_count`
 - `my_each` return single digit instead of array
 - update typo in `my_count` which results in error

Once updated, kindly resubmit fot review.

2019-05-27 04:04 UTC, inhaq commented on enumerable.rb
> +    return self.size unless block_give?
it should be `block_given?`

2019-05-27 21:23 UTC, inhaq requested changes
`my_each` is still not working properly. Let me add an example here as well.
`[1,2,3,4,5].my_each { |i| i }` returns `5` instead of `[1,2,3,4,5]`
As most of the methods depend on `my_each`, most probably they'll not work properly as well.
Once updated, kindly resubmit for review.

2019-05-28 09:55 UTC, NeerNim commented
> `my_each` is still not working properly. Let me add an example here as well.
> `[1,2,3,4,5].my_each { |i| i }` returns `5` instead of `[1,2,3,4,5]`
> As most of the methods depend on `my_each`, most probably they'll not work properly as well.
> Once updated, kindly resubmit for review.

I had to return self in my_each method

2019-05-28 15:03 UTC, inhaq commented
Hi @NeerNim it needs to return an array, instead of a number

2019-05-28 16:20 UTC, NeerNim commented
> Hi @NeerNim it needs to return an array, instead of a number

yes, I correct it to return array instead of number

2019-05-29 04:55 UTC, inhaq approved these changes
Awesome, It's 👍🏻
Before merging, kindly remove comments and `include Enumerable` is not required as well.
Good luck with the next projects.

2019-05-29 07:51 UTC, merged